### ISSUE TITLE
Network error when attempting to load a module

### ISSUE THREAD

**Issue by riko** [ClementDreptin/ModuleLoader2#1]
```
D:\xb>ModuleLoader.exe -s
xboxkrnl.exe
xam.xex
launch.xex
ximecore.xex
Xam.Community.xex
aac.xex
hud.xex
xbdm.xex
Tethered.Live
JRPC2.xex
RPC.xex
Nova.xex
xosc9v2.xex
default_mp.xex

D:\xb>ModuleLoader.exe -l HDD:\offhost\NiNJA\BO2.xex
[Error]: Unexpected network error
```

**Comment by ClementDreptin** [comment]
Please provide more info about what your environment is and what you did if you want help. Just providing a command output doesn't help much.
One thing I forgot to mention in the README is that you need XDRPC for ModuleLoader to work. It is pretty suprising that listing the loaded modules even worked.
You can also try to clear your system cache, it seems to solve a lot of issues when using any kind of stealth server.
